environment/teamGenerator/config/routes.rb
Rails.application.routes.draw do
  resources :difficulties
  resources :challenge_types
  resources :challenges
  resources :competitions
  resources :teams
  resources :countries
  resources :continents
  
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
end

environment/teamGenerator/app/models/challenge.rb
class Challenge < ApplicationRecord
    
  validates :name, presence: true, length: { maximum: 255 }
  belongs_to :team
  belongs_to :challenge_type
  belongs_to :difficulty

  def self.attr_accessible
    [
      :name, :challenge_type_id, :team_id, :difficulty_id
    ]
  end

end

environment/teamGenerator/app/models/challenge_type.rb
class ChallengeType < ApplicationRecord

  validates :name, presence: true, length: { maximum: 255 }
  has_many :challenges, dependent: :destroy

  def self.attr_accessible
    [
      :name
    ]
  end
end

environment/teamGenerator/app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]

  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url, notice: 'Challenge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def challenge_params
      params.require(:challenge).permit(:name, :team_id, :challenge_type)
    end
end

environment/teamGenerator/app/helpers/challenges_helper.rb
module ChallengesHelper
end

environment/teamGenerator/app/views/challenges/_form.html.erb
<%= form_with(model: challenge, local: true) do |form| %>
  <% if challenge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
      <% challenge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :challenge_name %>
  </div>

  <div class="field">
    <%= form.label :team_id %>
    <%= form.select :team_id, Team.all.collect { |p| [p.name, p.id] } %>
  </div>

  <div class="field">
    <%= form.label :challenge_type_id %>
    <%= form.select :challenge_type_id, ChallengeType.all.collect { |p| [p.name, p.id] }  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

environment/teamGenerator/app/views/challenges/edit.html.erb
<h1>Editing Challenge</h1>

<%= render 'form', challenge: @challenge %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>

environment/teamGenerator/app/views/challenges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Challenges</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Team</th>
      <th>Challenge type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @challenges.each do |challenge| %>
      <tr>
        <td><%= challenge.name %></td>
        <td><%= challenge.team.name %></td>
        <td><%= challenge.challenge_type.name %></td>
        <td><%= link_to 'Show', challenge %></td>
        <td><%= link_to 'Edit', edit_challenge_path(challenge) %></td>
        <td><%= link_to 'Destroy', challenge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Challenge', new_challenge_path %>

environment/teamGenerator/app/views/challenges/new.html.erb
<h1>New Challenge</h1>

<%= render 'form', challenge: @challenge %>

<%= link_to 'Back', challenges_path %>

environment/teamGenerator/app/views/challenges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @challenge.name %>
</p>

<p>
  <strong>Team:</strong>
  <%= @challenge.team.name %>
</p>

<p>
  <strong>Challenge type:</strong>
  <%= @challenge.challenge_type.name %>
</p>

<%= link_to 'Edit', edit_challenge_path(@challenge) %> |
<%= link_to 'Back', challenges_path %>