environment/teamGenerator/config/routes.rb
Rails.application.routes.draw do
  resources :difficulties
  resources :challenge_types
  resources :challenges
  resources :competitions
  resources :teams
  resources :countries
  resources :continents
  
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
end

environment/teamGenerator/app/models/continent.rb
class Continent < ApplicationRecord

    validates :name, presence: true, length: { maximum: 255 }
    has_many :countries, dependent: :destroy
  
    def self.attr_accessible
      [
        :name
      ]
    end

end

environment/teamGenerator/app/controllers/continents_controller.rb
class ContinentsController < ApplicationController
  before_action :set_continent, only: [:show, :edit, :update, :destroy]

  # GET /continents
  # GET /continents.json
  def index
    @continents = Continent.all
  end

  # GET /continents/1
  # GET /continents/1.json
  def show
  end

  # GET /continents/new
  def new
    @continent = Continent.new
  end

  # GET /continents/1/edit
  def edit
  end

  # POST /continents
  # POST /continents.json
  def create
    @continent = Continent.new(continent_params)

    respond_to do |format|
      if @continent.save
        format.html { redirect_to @continent, notice: 'Continent was successfully created.' }
        format.json { render :show, status: :created, location: @continent }
      else
        format.html { render :new }
        format.json { render json: @continent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /continents/1
  # PATCH/PUT /continents/1.json
  def update
    respond_to do |format|
      if @continent.update(continent_params)
        format.html { redirect_to @continent, notice: 'Continent was successfully updated.' }
        format.json { render :show, status: :ok, location: @continent }
      else
        format.html { render :edit }
        format.json { render json: @continent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /continents/1
  # DELETE /continents/1.json
  def destroy
    @continent.destroy
    respond_to do |format|
      format.html { redirect_to continents_url, notice: 'Continent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_continent
      @continent = Continent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def continent_params
      params.require(:continent).permit(:name)
    end
end

environment/teamGenerator/app/helpers/continents_helper.rb
module ContinentsHelper
end

environment/teamGenerator/app/views/continents/_form.html.erb
<%= form_with(model: continent, local: true) do |form| %>
  <% if continent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(continent.errors.count, "error") %> prohibited this continent from being saved:</h2>

      <ul>
      <% continent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :continent_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

environment/teamGenerator/app/views/continents/edit.html.erb
<h1>Editing Continent</h1>

<%= render 'form', continent: @continent %>

<%= link_to 'Show', @continent %> |
<%= link_to 'Back', continents_path %>

environment/teamGenerator/app/views/continents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Continents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @continents.each do |continent| %>
      <tr>
        <td><%= continent.name %></td>
        <td><%= link_to 'Show', continent %></td>
        <td><%= link_to 'Edit', edit_continent_path(continent) %></td>
        <td><%= link_to 'Destroy', continent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Continent', new_continent_path %>

environment/teamGenerator/app/views/continents/new.html.erb
<h1>New Continent</h1>

<%= render 'form', continent: @continent %>

<%= link_to 'Back', continents_path %>

environment/teamGenerator/app/views/continents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @continent.name %>
</p>

<%= link_to 'Edit', edit_continent_path(@continent) %> |
<%= link_to 'Back', continents_path %>