environment/teamGenerator/config/routes.rb
Rails.application.routes.draw do
  resources :difficulties
  resources :challenge_types
  resources :challenges
  resources :competitions
  resources :teams
  resources :countries
  resources :continents
  
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
end

environment/teamGenerator/app/models/difficulty.rb
class Difficulty < ApplicationRecord
    
  validates :name, presence: true, length: { maximum: 255 }
  has_many :challenges, dependent: :destroy

  def self.attr_accessible
    [
      :name
    ]
  end

end

environment/teamGenerator/app/controllers/difficulties_controller.rb
class DifficultiesController < ApplicationController
  before_action :set_difficulty, only: [:show, :edit, :update, :destroy]

  # GET /difficulties
  # GET /difficulties.json
  def index
    @difficulties = Difficulty.all
  end

  # GET /difficulties/1
  # GET /difficulties/1.json
  def show
  end

  # GET /difficulties/new
  def new
    @difficulty = Difficulty.new
  end

  # GET /difficulties/1/edit
  def edit
  end

  # POST /difficulties
  # POST /difficulties.json
  def create
    @difficulty = Difficulty.new(difficulty_params)

    respond_to do |format|
      if @difficulty.save
        format.html { redirect_to @difficulty, notice: 'Difficulty was successfully created.' }
        format.json { render :show, status: :created, location: @difficulty }
      else
        format.html { render :new }
        format.json { render json: @difficulty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /difficulties/1
  # PATCH/PUT /difficulties/1.json
  def update
    respond_to do |format|
      if @difficulty.update(difficulty_params)
        format.html { redirect_to @difficulty, notice: 'Difficulty was successfully updated.' }
        format.json { render :show, status: :ok, location: @difficulty }
      else
        format.html { render :edit }
        format.json { render json: @difficulty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /difficulties/1
  # DELETE /difficulties/1.json
  def destroy
    @difficulty.destroy
    respond_to do |format|
      format.html { redirect_to difficulties_url, notice: 'Difficulty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_difficulty
      @difficulty = Difficulty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def difficulty_params
      params.require(:difficulty).permit(:name)
    end
end

environment/teamGenerator/app/helpers/difficulties_helper.rb
module DifficultiesHelper
end

environment/teamGenerator/app/views/difficulties/_form.html.erb
<%= form_with(model: difficulty, local: true) do |form| %>
  <% if difficulty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(difficulty.errors.count, "error") %> prohibited this difficulty from being saved:</h2>

      <ul>
      <% difficulty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :difficulty_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

environment/teamGenerator/app/views/difficulties/edit.html.erb
<h1>Editing Difficulty</h1>

<%= render 'form', difficulty: @difficulty %>

<%= link_to 'Show', @difficulty %> |
<%= link_to 'Back', difficulties_path %>

environment/teamGenerator/app/views/difficulties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Difficulties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @difficulties.each do |difficulty| %>
      <tr>
        <td><%= difficulty.name %></td>
        <td><%= link_to 'Show', difficulty %></td>
        <td><%= link_to 'Edit', edit_difficulty_path(difficulty) %></td>
        <td><%= link_to 'Destroy', difficulty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Difficulty', new_difficulty_path %>

environment/teamGenerator/app/views/difficulties/new.html.erb
<h1>New Difficulty</h1>

<%= render 'form', difficulty: @difficulty %>

<%= link_to 'Back', difficulties_path %>

environment/teamGenerator/app/views/difficulties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @difficulty.name %>
</p>

<%= link_to 'Edit', edit_difficulty_path(@difficulty) %> |
<%= link_to 'Back', difficulties_path %>